version: '3'

services:
# 后端
  subconverter:
    image: tindy2013/subconverter:latest
    container_name: subconverter
    ports:
      - "25500:25500"
    restart: always
    networks:
      - subweb-network

# 前端
  subweb:
    image: stilleshan/subweb
    container_name: subweb
    ports:
      - "18080:80"
    volumes:
      - ./subweb/public/conf:/usr/share/nginx/html/conf
    environment:
      - SITE_NAME=my-subweb
      - API_URL=http://ip:25500
      - SHORT_URL=
    depends_on:
      - subconverter
    restart: always
    networks:
      - subweb-network

networks:
  subweb-network:
    driver: bridge
